[phases.setup]
nixPkgs = ["nodejs-18_x"]

[phases.install]
cmds = ["cd frontend && npm ci --legacy-peer-deps"]

[phases.build]
cmds = ["cd frontend && npm run build"]

[start]
cmd = "npx serve@14.2.1 frontend/dist -s -p $PORT"